services:
  db:
    image: postgres:16-alpine
    container_name: hiddenvalley-db
    restart: always 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Umg12345
      POSTGRES_DB: HiddenValleyDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./HiddenValley.API
      dockerfile: Dockerfile
    ports:
      - "7084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=HiddenValleyDB;Username=admin;Password=Umg12345
    depends_on:
      - db

  frontend:
    build:
      context: ./HiddenValley.Frontend
      dockerfile: Dockerfile
    ports:
      - "7075:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api

volumes:
  postgres_data: